{
 "title": "Kubernetes Overview",
 "tags": [
  "kubernetes",
  "monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "HTTP Requests Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])" }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=~\"5..\"}[1m])"
    }
   ]
  }
 ]
}