# Config map for metrics scraping

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf # config name
  labels:
    name: prometheus-conf
  namespace: monitoring
data:
  prometheus.yml: |- # insert yaml file directly into config
    global:
      scrape_interval: 15s # time interval for scraping
    scrape_configs:
      - job_name: 'backend'
        static_configs:
          - targets:
            - "backend-service:80" # address from which metrics are collected via /metrics endpoint