# Prometheus Service account to bind to Prometheus role with needed permissions

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa # Prometheus service account name
  namespace: monitoring