apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: rustycloud-pvc

spec:
  volumeName: rustycloud-pv

  storageClassName: ""

  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 10Gi