apiVersion: v1
kind: Secret

metadata:
  name: mongo-creds # used by statefulset to pull credentials
  namespace: database

type: Opaque # Generic secret type to store key-value pairs

stringData:
  username: ${MONGODB_USER}
  password: ${MONGODB_PASS}